"""Stage 6: compare a fresh reproduction against this project's outputs.

Usage (from project root):
    .venv\\Scripts\\python scripts\\compare_reproduction.py D:\\hynix_repro

Compares every JSON result both roots have (ignoring timing fields), the cleaned
data's split/component columns, and the final CNN block. A reproduction that was
cloned from git also holds the committed outputs, so a file only counts if it was
rewritten after the reproduction downloaded its data (else STALE). Prints MATCH /
DIFF / STALE per file and exits non-zero on any DIFF or STALE.
"""
import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
FILES = ["outputs/eda/summary.json", "outputs/splits/split_summary.json", "outputs/splits/split_seed_variance.json",
         "outputs/baseline/results.json", "outputs/cnn/main_ce/history.json"]
TIMING = {"fit_seconds", "total_seconds", "seconds"}


def strip_timing(x):
    if isinstance(x, dict):
        return {k: strip_timing(v) for k, v in x.items() if k not in TIMING}
    if isinstance(x, list):
        return [strip_timing(v) for v in x]
    return x


def diffs(a, b, path=""):
    if isinstance(a, dict) and isinstance(b, dict):
        for k in sorted(set(a) | set(b)):
            if k not in a or k not in b:
                yield f"{path}/{k}: only in {'original' if k in a else 'reproduction'}"
            else:
                yield from diffs(a[k], b[k], f"{path}/{k}")
    elif isinstance(a, list) and isinstance(b, list) and len(a) == len(b):
        for i, (x, y) in enumerate(zip(a, b)):
            yield from diffs(x, y, f"{path}[{i}]")
    elif a != b:
        yield f"{path}: {a!r} != {b!r}"


def main():
    other = Path(sys.argv[1])
    started = (other / "data" / "raw" / "LSWMD.pkl").stat().st_mtime  # data downloaded after cloning
    fresh = lambda f: f.exists() and f.stat().st_mtime > started  # noqa: E731
    failed = False
    for rel in FILES:
        a, b = ROOT / rel, other / rel
        if not fresh(b):
            print(f"[STALE] {rel}: not regenerated by the reproduction")
            failed = True
            continue
        d = list(diffs(strip_timing(json.loads(a.read_text(encoding="utf-8"))),
                       strip_timing(json.loads(b.read_text(encoding="utf-8")))))
        print(f"[{'MATCH' if not d else 'DIFF '}] {rel}" + "".join(f"\n    {x}" for x in d[:10]))
        failed |= bool(d)

    cols = ["label", "lotName", "component", "split_main", "split_random"]
    pa, pb = ROOT / "data/processed/labeled_clean.pkl", other / "data/processed/labeled_clean.pkl"
    if pb.exists():
        a, b = pd.read_pickle(pa)[cols], pd.read_pickle(pb)[cols]
        same = a.index.equals(b.index) and a.equals(b)
        print(f"[{'MATCH' if same else 'DIFF '}] data/processed/labeled_clean.pkl columns {cols}")
        failed |= not same

    cb = other / "outputs/cnn/results.json"
    if not fresh(cb):
        print("[STALE] outputs/cnn/results.json: not regenerated by the reproduction")
        failed = True
    else:
        ra = json.loads((ROOT / "outputs/cnn/results.json").read_text(encoding="utf-8"))
        rb = json.loads(cb.read_text(encoding="utf-8"))
        for key in ("final", "baseline_bar", "success"):
            d = list(diffs(ra[key], rb[key]))
            print(f"[{'MATCH' if not d else 'DIFF '}] outputs/cnn/results.json[{key}]" + "".join(f"\n    {x}" for x in d[:10]))
            failed |= bool(d)
        d = list(diffs(strip_timing(ra["runs"]["main_ce"]), strip_timing(rb["runs"]["main_ce"])))
        print(f"[{'MATCH' if not d else 'DIFF '}] outputs/cnn/results.json[runs][main_ce]" + "".join(f"\n    {x}" for x in d[:10]))
        failed |= bool(d)
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
